version: "3"
services:

## SSL Front End
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf.d:/etc/nginx/conf.d
      - nginx-vhost.d:/etc/nginx/vhost.d
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-data:/usr/share/nginx/html
    logging:
      options:
        max-size: '4m'
        max-file: '10'
    networks:
      - frontend

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - nginx-conf.d:/etc/nginx/conf.d
      - nginx-vhost.d:/etc/nginx/vhost.d
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-data:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      options:
        max-size: '2m'
        max-file: '10'
    networks:
      - frontend

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - nginx-conf.d:/etc/nginx/conf.d
      - nginx-vhost.d:/etc/nginx/vhost.d
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-data:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-proxy
    logging:
      options:
        max-size: '2m'
        max-file: '10'
    networks:
      - frontend

## Veleda Frontend
  nginx-web:
    build: nginx
    container_name: nginx-web
    env_file:
      - 'nginx/env.nginx'
    volumes:
      - jekyll-data:/usr/share/nginx/html
    logging:
      options:
        max-size: '4m'
        max-file: '10'
    networks:
      - frontend

#  core:
#    build: ./core
#    container_name: core
#    ports:
#      - "8001:8001"
#    env_file:
#      - 'web/secrets.flask'
#      - 'grafana/secrets.grafana'
#      - 'grafana/env.grafana'
#    networks:
#      - backend
#      - frontend
#    command: bash -c "./start.sh"
#    depends_on:
#      - influxdb
#      - grafana
#      - postgres
#      - redis

#  grafana:
#    image: grafana/grafana:4.6.3
#    container_name: grafana
#    env_file:
#      - 'grafana/env.grafana'
#      - 'grafana/secrets.grafana'
#    environment:
#      - VIRTUAL_HOST=data.staging.veleda.io
#      - LETSENCRYPT_HOST=data.staging.veleda.io
#      - LETSENCRYPT_EMAIL=moritz.ulmer@posteo.de
#      - LETSENCRYPT_TEST=true
#    networks:
#      - backend
#      - frontend
#    volumes:
#      - grafana-data:/var/lib/grafana
#    depends_on:
#      - influxdb

## Veleda Backend
#  postgres:
#    build: ./postgres
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    env_file:
#      - 'postgres/secrets.postgres'
#    networks:
#      - backend
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

#  redis:
#    image: redis:3.2
#    container_name: redis
#    networks:
#      - backend

#  influxdb:
#    image: influxdb:latest
#    container_name: influxdb
#    ports:
#      - "8086:8086"
#    env_file:
#      - 'influxdb/env.influxdb'
#      - 'influxdb/secrets.influxdb'
#    networks:
#      - backend
#    volumes:
#      - influxdb-data:/var/lib/influxdb

networks:
#  backend:
  frontend:

volumes:
  influxdb-data:
  grafana-data:
  postgres-data:
  jekyll-data:
  
  nginx-conf.d:
  nginx-vhost.d:
  nginx-certs:
  nginx-data:
