# Site settings
title: Veleda
email: moritz.ulmer@posteo.de

source: app
destination: web

description: >
  An open-source data analytics platform designed for hydroponic systems.
  Scaling all the way from single DIY builds up to commercial scale setups. In
  collaboration with HAPI (Hydroponic Automation Platform Initative), it
  digitalizes and visualizes your grow system.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://veleda.io" # the base hostname & protocol for your site
encoding: utf-8

twitter_username: moritz89
github_username:  moritz89

# Build settings
markdown: kramdown
